config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  mount RailsAdmin::Engine => '/sarfraz', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/index'=>"posts#index"
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'posts#land'

   resources :posts do
    resources :fors
    resources :againsts
  end

  
end

app/models/against.rb
class Against < ApplicationRecord
  validates :user, presence: true
  belongs_to :post, optional: true
  belongs_to :user, optional:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/for.rb
class For < ApplicationRecord
  validates :user, presence: true
  belongs_to :post, optional: true
  belongs_to :user,optional: true 
end

app/models/post.rb
class Post < ApplicationRecord
  	validates :user, presence: true
	has_many :fors, dependent: :destroy
	has_many :againsts, dependent: :destroy
	belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_many :fors
	has_many :againsts
	class << self
  		def from_omniauth(auth_hash)
  			# where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    			user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
		    	user.name = auth_hash['info']['name']
		    	user.image_url = auth_hash['info']['image']
		    	user.url = auth_hash['info']['urls'][user.provider.capitalize]
		    	user.save!
		    	user
		    # end
  		end
	end
end

app/controllers/againsts_controller.rb
class AgainstsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@against = @post.againsts.create(againsts_params)
		@against.user = current_user
		@against.save
		redirect_to post_path(@post)
  	end

  private
    def againsts_params
      params.require(:against).permit(:content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

def current_user
  @current_user ||= User.find_by(id: session[:user_id])
end

helper_method :current_user
end

app/controllers/fors_controller.rb
class ForsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@for = @post.fors.new(fors_params)
		@for.user = current_user
            @for.save
		redirect_to post_path(@post)
  	end

  	

  private
    def fors_params
      params.require(:for).permit(:content)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def land
	end

	def show 
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end
 private
    def post_params
      params.require(:post).permit(:title)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	begin
    		@user = User.from_omniauth(request.env['omniauth.auth'])
    		session[:user_id] = @user.id
   		 # flash[:success] = "Welcome, #{@user.name}!"
  	rescue
    		# flash[:warning] = "There was an error while trying to authenticate you..."
  	end
  	redirect_to root_path
end

    def destroy
    if current_user
        session.delete(:user_id)
          # flash[:success] = 'See you!'
      end
      redirect_to root_path
  end 
end

app/helpers/againsts_helper.rb
module AgainstsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fors_helper.rb
module ForsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/againsts/_form.html.erb
<%= form_for([@post, @post.againsts.build]) do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <br>
  <p>
    <%=f.submit%>
  </p>

<%end%>

app/views/fors/_form.html.erb
<%= form_for([@post, @post.fors.build]) do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <br>
  <p>
    <%=f.submit%>
  </p>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>Debate</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  </head>

  <body>
	  <div id="modal1" class="modal">
	    <div class="modal-content center">
	    <h4>Sign Up</h4>
	    <p>Sign up with your social media account to debate and add your own topics</p>
	     <%= link_to 'Twitter', '/auth/twitter', :class => "btn twitter"%>	
          	     <%= link_to 'Facebook', '/auth/facebook',:class =>"btn facebook" %>
	    </div>
	  </div>

	<nav class="blue lighten-2">
	  <div class="nav-wrapper">
		<a href="#" class="brand-logo">DEBATING SOCIETY</a>
		<ul id="nav-mobile" class="right hide-on-med-and-down">
		  <li><%= link_to "Home", root_path%></li>
		  <li><%= link_to "Debate", posts_path%></li>

		  <% if current_user %>
          		<li><%= image_tag current_user.image_url, alt: current_user.name %></li>
          		<li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        
      		<% else %>
		  <li><a class="waves-effect waves-light btn modal-trigger" href="#modal1">Sign In / Sign Up</a></li>
          		 <% end %>
        		</ul>
     		
	  </div>
	</nav>
	<%= yield %>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error")%> prevented
        this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%=f.submit%>
<%end%>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<h1><%=link_to post.title,post%></h1>
 <%end%>


<%= link_to "New Topic", new_post_path%>

app/views/posts/land.html.erb
  
 <div class="slider">
		<ul class="slides">
			<li>
				<img src="https://lorempixel.com/580/250/nature/1"> <!-- random image -->
				<div class="caption center-align">
					<h3>DEBATING SOCIETY</h3>
					<h5 class="light grey-text text-lighten-3">"If we agreed that easily, we will be having a quote here"</h5>
				</div>
			</li>
			<li>
				<img src="https://lorempixel.com/580/250/nature/2"> <!-- random image -->
				<div class="caption left-align">
					<h3>Left Aligned Caption</h3>
					<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
				</div>
			</li>
			<li>
				<img src="https://lorempixel.com/580/250/nature/3"> <!-- random image -->
				<div class="caption right-align">
					<h3>Right Aligned Caption</h3>
					<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
				</div>
			</li>
			<li>
				<img src="https://lorempixel.com/580/250/nature/4"> <!-- random image -->
				<div class="caption center-align">
					<h3>This is our big Tagline!</h3>
					<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
				</div>
			</li>
		</ul>
</div>

<div class="topic center">
	<h3>What Do We do?</h5>
</div>

<div class="what_do_we_do container">
	<div class="row center">

	      <div class="col s4 bullet">
	        <!-- Promo Content 1 goes here -->
	        <h5>Debate!!!</h5>
	        <p>
	        	Of course we debate. Formal ,informal, parliamentary. You name it and chances are we will be doing it.
	        </p>

	      </div>
	      <div class="col s4 bullet">
	        <!-- Promo Content 2 goes here -->
	        <h5>Workshops</h5>
	        <p>Workshops to teach everyone the art of debating. Weekly classes to help students overcome fear of stage and bring out the best in him.</p>
	      </div>
	      <div class="col s4 bullet">
	        <!-- Promo Content 3 goes here -->
	        <h5>Gymkhana Debates</h5>
	        <p>
	        	Doing debates during the gymkhana to help you get a better perspective of the candidates.
	        </p>
	      </div>

    </div>

    <div class="row center">

	      <div class="col s4 bullet">
	        <!-- Promo Content 1 goes here -->
	        <h5>Online Debate</h5>
	        <p>
	        	Online debates for those introverts who are shy to express themselves on the stage. Now argue from the comfort of your room.
	        </p>

	      </div>
	      <div class="col s4 bullet">
	        <!-- Promo Content 2 goes here -->
	        <h5>Events</h5>
	        <p>
	        	You will find us in almost all the fests in the college. We add the spice in the fests through our fiery debating events 
	        </p>
	      </div>
	      <div class="col s4 bullet">
	        <!-- Promo Content 3 goes here -->
	        <h5>Manthan</h5>
	        <p>
	        	Brainstorm to make your college life even better. 
	        </p>
	      </div>

    </div>
</div>

app/views/posts/new.html.erb
<%=render 'form'%>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>
 


<div class="fort">
<h3>For the motion</h3>
<% if @post.fors.count>0%>
<%@post.fors.each do |post_for|%>
	<p><%=post_for.content%></p>
	<p><%=post_for.user.name%></p>
<%end%> 
    <%else%>
    <h4>No for comments till now</h4>
    <%end%>      
    <%= render "fors/form", fors: @user%>
  </div>


<div class="against">
	<h3>Against the motion</h3>
      <% if @post.againsts.count>0%>
	     <%@post.againsts.each do |f|%>
		<p><%=f.content%></p>
		<p><%= f.user.name%></p>
	<%end%> 
      <%else%>
          <h4>No against comments till now</h4>
          <%end%>	
         <%= render "againsts/form"%>

</div>